name: Web Container CI
on:
  push:
    branches: 
      - main
      - '**'  # This will match any branch
    paths:
      - 'web-container/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'web-container/**'
      - '.github/workflows/web-ci.yml'
jobs:
  test-web-container:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd web-container
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-flask pytest-cov requests

    - name: Run tests
      run: |
        cd web-container
        pytest ../tests/web/test_app.py ../tests/web/test_api_request.py ../tests/web/test_routes.py -v
    
    - name: Generate coverage report
      run: |
        cd web-container
        pytest --cov=. ../tests/web/ --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./web-container/coverage.xml
        flags: webcontainer
        fail_ci_if_error: false
