name: Web Container CI/CD

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - 'web-container/**'
      - '.github/workflows/web-container-ci-cd.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'web-container/**'
      - '.github/workflows/web-container-ci-cd.yml'

jobs:
  test-web-container:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd web-container
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-flask pytest-cov requests
          
      - name: Run tests
        run: |
          cd web-container
          pytest tests/test_app.py --cov=app
          
      - name: Check test coverage
        run: |
          cd web-container
          pytest tests/test_app.py --cov=app --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./web-container/coverage.xml
          flags: web-container
          fail_ci_if_error: false